CREATE TABLE Users (
    UserID SERIAL PRIMARY KEY,
    Username VARCHAR(50) UNIQUE NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    JoinDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Categories (
    CategoryID SERIAL PRIMARY KEY,
    Name VARCHAR(100) UNIQUE NOT NULL,
    Description TEXT
);
CREATE TABLE Posts (
    PostID SERIAL PRIMARY KEY,
    UserID INT REFERENCES Users(UserID) ON DELETE CASCADE,
    CategoryID INT REFERENCES Categories(CategoryID) ON DELETE SET NULL,
    Title VARCHAR(300) NOT NULL,
    Body TEXT,
    Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Comments (
    CommentID SERIAL PRIMARY KEY,
    PostID INT REFERENCES Posts(PostID) ON DELETE CASCADE,
    UserID INT REFERENCES Users(UserID) ON DELETE CASCADE,
    Body TEXT NOT NULL,
    Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Votes (
    VoteID SERIAL PRIMARY KEY,
    UserID INT REFERENCES Users(UserID) ON DELETE CASCADE,
    PostID INT REFERENCES Posts(PostID) ON DELETE CASCADE,
    VoteType SMALLINT CHECK (VoteType IN (1, -1)) NOT NULL,
    Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Moderators (
    ModeratorID SERIAL PRIMARY KEY,
    UserID INT REFERENCES Users(UserID) ON DELETE CASCADE,
    CategoryID INT REFERENCES Categories(CategoryID) ON DELETE CASCADE,
    AssignedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Reports (
    ReportID SERIAL PRIMARY KEY,
    UserID INT REFERENCES Users(UserID) ON DELETE CASCADE,
    PostID INT REFERENCES Posts(PostID) ON DELETE CASCADE,
    Reason TEXT NOT NULL,
    Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Messages (
    MessageID SERIAL PRIMARY KEY,
    SenderID INT REFERENCES Users(UserID) ON DELETE CASCADE,
    ReceiverID INT REFERENCES Users(UserID) ON DELETE CASCADE,
    Body TEXT NOT NULL,
    Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Followers (
    FollowerID SERIAL PRIMARY KEY,
    FollowerUserID INT REFERENCES Users(UserID) ON DELETE CASCADE,
    FollowedUserID INT REFERENCES Users(UserID) ON DELETE CASCADE,
    Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Notifications (
    NotificationID SERIAL PRIMARY KEY,
    UserID INT REFERENCES Users(UserID) ON DELETE CASCADE,
    Message TEXT NOT NULL,
    IsRead BOOLEAN DEFAULT FALSE,
    Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);